#%RAML 1.0
title: azure-project-v85
version: v1
baseUri: https://azure-project-v85.example.com/{version}
mediaType: application/json

/leads:
  post:
    description: "Create a new leads"
    displayName: "Create Leads"
    body:
      application/json:
        type: !include resources/schemas/PostLeadsRequest.raml
        example: !include resources/examples/PostLeadsRequest.json
    responses:
      200:
        body:
          application/json:
            type: !include resources/schemas/PostLeadsResponse.raml
            example: !include resources/examples/PostLeadsResponse.json

/lead/{id}:
  uriParameters:
    id:
      type: integer
      required: true
  get:
    description: "Retrieve a specific lead by ID"
    displayName: "Get Lead"
    responses:
      200:
        body:
          application/json:
            type: !include resources/schemas/GetLeadIdResponse.raml
            example: !include resources/examples/GetLeadIdResponse.json
  put:
    description: "Update an existing lead"
    displayName: "Update Lead"
    body:
      application/json:
        type: !include resources/schemas/PutLeadIdRequest.raml
        example: !include resources/examples/PutLeadIdRequest.json
    responses:
      200:
        body:
          application/json:
            type: !include resources/schemas/PutLeadIdResponse.raml
            example: !include resources/examples/PutLeadIdResponse.json
  delete:
    description: "Delete a specific lead"
    displayName: "Delete Lead"
    responses:
      200:
        body:
          application/json:
            type: !include resources/schemas/DeleteLeadIdResponse.raml
            example: !include resources/examples/DeleteLeadIdResponse.json

/opportunities:
  post:
    description: "Create a new opportunities"
    displayName: "Create Opportunities"
    body:
      application/json:
        type: !include resources/schemas/PostOpportunitiesRequest.raml
        example: !include resources/examples/PostOpportunitiesRequest.json
    responses:
      200:
        body:
          application/json:
            type: !include resources/schemas/PostOpportunitiesResponse.raml
            example: !include resources/examples/PostOpportunitiesResponse.json

/opportunity/{id}:
  uriParameters:
    id:
      type: integer
      required: true
  get:
    description: "Retrieve a specific opportunity by ID"
    displayName: "Get Opportunity"
    responses:
      200:
        body:
          application/json:
            type: !include resources/schemas/GetOpportunityIdResponse.raml
            example: !include resources/examples/GetOpportunityIdResponse.json
  put:
    description: "Update an existing opportunity"
    displayName: "Update Opportunity"
    body:
      application/json:
        type: !include resources/schemas/PutOpportunityIdRequest.raml
        example: !include resources/examples/PutOpportunityIdRequest.json
    responses:
      200:
        body:
          application/json:
            type: !include resources/schemas/PutOpportunityIdResponse.raml
            example: !include resources/examples/PutOpportunityIdResponse.json
  delete:
    description: "Delete a specific opportunity"
    displayName: "Delete Opportunity"
    responses:
      200:
        body:
          application/json:
            type: !include resources/schemas/DeleteOpportunityIdResponse.raml
            example: !include resources/examples/DeleteOpportunityIdResponse.json

/health:
  get:
    description: "Retrieve all health"
    displayName: "Get Health"
    responses:
      200:
        body:
          application/json:
            type: !include resources/schemas/GetHealthResponse.raml
            example: !include resources/examples/GetHealthResponse.json
